version: "3.8"
services:
  web:
    build: .
    command: ["uvicorn", "app.src.app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - PYTHO ?
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    container_name: redis
    command:
    ports:
      - "6379:6379"
  
  worker:
    build: .
    working_dir: /app  
    command: >
      sh -c "export PYTHONPATH=$$PYTHONPATH:/app/async_fastapi_image && \
              celery -A app.src.app:celery worker --loglevel=info"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/async_fastapi_image
    depends_on:
      - redis